[project]
name = "llm_stream_manager"
version = "0.1.0"
description = "Lightweight LLM stream management library"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
